replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/my-kubernetes-project-456905/hello-world-jenkins-repo/hello-world
  tag: ""
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80

serviceAccount:
  create: true
  name: helm-ksa
