apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  type: {{ .Values.service.type }}
  selector:
    app: hello-world
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
